### ISSUE TITLE
Some AnimatedVectorDrawables are blurry on a Nexus 4 device running L (5.1.1)

### ISSUE THREAD

**Issue by amilcar-andrade** [alexjlockwood/adp-delightful-details#1] opened 2016-11-29 23:45 UTC
Attached are some screenshots that I took while running the demo app on my Nexus 4 device.

![screenshot_2016-11-29-13-54-58 1](https://cloud.githubusercontent.com/assets/802308/20733845/b5f81a9e-b663-11e6-9b0b-e0f20872b334.png)

![screenshot_2016-11-29-14-48-15](https://cloud.githubusercontent.com/assets/802308/20733848/b7ab1f44-b663-11e6-8a76-af0685d1b049.png)

![screenshot_2016-11-29-13-52-32 1](https://cloud.githubusercontent.com/assets/802308/20733851/bbaa3abc-b663-11e6-8dfd-aed42070b438.png)

![screenshot_2016-11-29-14-48-02](https://cloud.githubusercontent.com/assets/802308/20733855/bee7d054-b663-11e6-8f2e-ad8296310edd.png)

![screenshot_2016-11-29-18-44-39](https://cloud.githubusercontent.com/assets/802308/20733906/021bd12c-b664-11e6-86cc-52a3fd9bc53c.png)

![screenshot_2016-11-29-18-44-12](https://cloud.githubusercontent.com/assets/802308/20733905/ff6526e0-b663-11e6-8e1c-147cb80f8834.png)

I did some investigation and it seems that in some cases the problem is due to the fact of specifying the size instead of just using `wrap_content`. I changed the `width` and `height` properties of the `ImageViews` inside the `activity_checkable` layout and all of them were able to render correctly. 

I thought `vectors` were supposed to be of any size without causing any quality problems.

**Comment by amilcar-andrade** [comment] 2016-11-29 23:46
@alexjlockwood created issue based on the [Google+ comment](https://plus.google.com/u/0/+AlexLockwood/posts/MnTpmroSfPx)

**Comment by alexjlockwood** [comment] 2016-11-30 01:35
Hmm... interesting. Will look into this!

**Comment by alexjlockwood** [comment] 2016-11-30 18:31
Well, it seems like the issue is that we are using `AnimatedStateListDrawable`... and this inflates its children drawables using the framework `VectorDrawable` class (instead of as `VectorDrawableCompat` drawables, which are usually used on Android 5.0 and 5.1 to address some bugs in the framework implementation that weren't fixed until Android 6.0). 

Not sure what the best way to work around this is yet... the first thing I tried was creating the `AnimatedStateListDrawable` programatically like below, but that gave me a crash on Lollipop. Will continue looking at this...

```java
AnimatedStateListDrawable asl = new AnimatedStateListDrawable();
asl.addState(
    new int[]{android.R.attr.state_checked},
    AppCompatResources.getDrawable(this, R.drawable.vd_checkable_checkbox_checked),
    R.id.checked);
asl.addState(
    new int[0],
    AppCompatResources.getDrawable(this, R.drawable.vd_checkable_checkbox_unchecked),
    R.id.unchecked);
asl.addTransition(
    R.id.unchecked,
    R.id.checked,
    AnimatedVectorDrawableCompat.create(this, R.drawable.avd_checkable_checkbox_unchecked_to_checked),
    true);
asl.addTransition(
    R.id.checked,
    R.id.unchecked,
    AnimatedVectorDrawableCompat.create(this, R.drawable.avd_checkable_checkbox_checked_to_unchecked),
    true);
checkBoxView.setImageDrawable(asl);
```

**Comment by alexjlockwood** [comment] 2016-12-08 15:01
I talked to one of the members of the framework team and they said that the crash I encountered when creating the `AnimatedStateListDrawable` programatically was a known issue and will be fixed in an upcoming support library release. Once that is checked in, I think this should be fix-able by creating the `AnimatedStateListDrawable` programatically as shown in the sample code above (or you could simply not use `AnimatedStateListDrawable` all together and manually start/stop the animated vectors yourself).

To be absolutely clear, the blurriness is a bug in the framework implementation of vector drawables/animated vector drawables. The Android team in MTV acknowledged these bugs as serious and so they decided that on Android 5.0 and 5.1 it should opt to use the support library vector drawable/animated vector drawable instead. However, our usage of `AnimatedStateListDrawable` in this sample app is annoyingly preventing us from using the support library vector drawbles... hence the reason we are seeing the bug.

**Comment by alexjlockwood** [comment] 2016-12-08 15:03
You can fix the blurriness by setting the vector drawable width/height to be the same size as used in the activity layout. This obviously isn't ideal, since it kind of defeats the purpose of the vectors being scale-able on any screen density. As for the tinting issues (i.e. how you can see the paths overlapping on top of each other in the screenshots above), I have no idea how that can be fixed aside from somehow using the support library vector drawables instead of the framework implementation.

Please LMK if this is clear and/or if you have any other questions!

**Comment by amilcar-andrade** [comment] 2016-12-08 15:11
@alexjlockwood thanks so much for taking the time to explaining the whole thing. It is surprising how a small bug can lead to this investigation and discover all of these things. Thanks again for taking the time to investigate.

As a side note, It is a pity that you must specify the width or height. I thought that was one benefit of using vectors. That was one of the fundamental points in this video https://www.youtube.com/watch?v=wlFVIIstKmA

**Comment by amilcar-andrade** [comment] 2016-12-08 15:21
@alexjlockwood do you want me to close this issue?

**Comment by alexjlockwood** [comment] 2016-12-08 18:27
No, you can keep it open... at least until the next version of the support library comes out.

Scaling is definitely one of the fundamental benefits of vector drawables. The issue is just that there are bugs in Android 5.0 and 5.1 that cause the blurriness you're seeing. The VectorDrawableCompat libraries don't have these issues, which is why using them is preferred on Android 5.0 and 5.1.

**Comment by nickbutcher** [comment] 2016-12-09 17:00
> As for the tinting issues (i.e. how you can see the paths overlapping on top of each other in the screenshots above)

This is just an artifact of how the paths are drawn i.e. overlapping shapes. When you use a semi-transparent tint (looks like `?android:colorControlNormal` in the screenshot?) you'll get this kind of effect. You can avoid this by either using an opaque color or by altering the paths to avoid overlaps (like the paths making the arrow in the arrow <-> burger anim).

**Comment by alexjlockwood** [comment] 2016-12-09 18:56
The issue only seems to happen on 5.0 and 5.1, which is why it seems so weird. For the most part, the vectors in this project use `@android:color/white` as the fill/stroke color and use `?attr/colorControlNormal` as the tint. Vectors use `src_in` as the default tint mode, so that means all of the opaque pixels (i.e. all of the white paths) should be replaced with the value pointed to by `?attr/colorControlNormal`, right? This is how things behave on API 23+ but I have no idea what's going on on API 21-22... I assume it must be a bug in the framework.

**Comment by alexjlockwood** [comment] 2018-09-25 15:50
This should be fixed now if you use support lib v28 or above. Under-the-hood an `AnimatedStateListDrawableCompat` will be used instead of an `AnimatedStateListDrawable`, and that will ensure that the support lib vectors/animated vectors will be used instead of the framework implementations.

**Closed as completed by alexjlockwood** 2018-09-25 15:50 UTC
Labels: bug

**Comment by mahozad** [comment] 2019-07-28 11:49
For me the reason that caused vectors to be converted to png was `android:fillType="..."` attribute in my vector drawable. When I **removed all occurrences of this attribute in my drawable**, next time the app was compiled everything was fine.
